sudo: required
services:
  - docker

before_install:
  - docker build -t sahninitesh19/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sahninitesh19/react-test npm run test -- --coverage

after_success:
  - docker build -t sahninitesh19/multi-client ./client
  - docker build -t sahninitesh19/multi-nginx ./nginx
  - docker build -t sahninitesh19/multi-server ./server
  - docker build -t sahninitesh19/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push sahninitesh19/multi-client
  - docker push sahninitesh19/multi-nginx
  - docker push sahninitesh19/multi-server
  - docker push sahninitesh19/multi-worker


